/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  REGISTER: '/register',
  REGISTER_SUCCESS: '/register-success',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '*',
  
  // Feature module route prefixes (prepared for future steps)
  DASHBOARD: '/dashboard',
  DASHBOARD_SUPER_ADMIN: '/dashboard/super-admin',
  DASHBOARD_ADMIN: '/dashboard/admin',
  DASHBOARD_TEACHER: '/dashboard/teacher',
  DASHBOARD_STUDENT: '/dashboard/student',
  DASHBOARD_PARENT: '/dashboard/parent',
  ATTENDANCE: '/attendance',
  RESULTS: '/results',
  COURSES: '/courses',
  DEPARTMENTS: '/departments',
  PROGRAMS: '/programs',
  SEMESTERS: '/semesters',
  SECTIONS: '/sections',
  TEACHERS: '/teachers',
  STUDENTS: '/students',
  PARENTS: '/parents',
  NOTIFICATIONS: '/notifications',
  REPORTS: '/reports',
  FEES: '/fees',
  TIMETABLE: '/timetable',
  ASSIGNMENTS: '/assignments',
  QUIZZES: '/quizzes',
  EXAMS: '/exams',
  USERS: '/users',
  ANALYTICS: '/analytics',
  SUBJECTS: '/subjects',
  COURSE_OFFERINGS: '/course-offerings',
  ENROLLMENTS: '/enrollments',
  ENROLLMENTS_CREATE: '/enrollments/create',
  ENROLLMENTS_EDIT: '/enrollments/:id/edit',
  ENROLLMENTS_DETAIL: '/enrollments/:id',
  LEAVES: '/leaves',
  LEAVES_CREATE: '/leaves/create',
  LEAVES_DETAIL: '/leaves/:id',
  TRANSCRIPTS: '/transcripts',
  TRANSCRIPTS_VERIFY: '/verify-transcript',
  DEGREE_AUDIT: '/degree-audit',
  ALUMNI: '/alumni',
  PLACEMENT: '/placement',
  HOSTEL: '/hostel',
  TRANSPORT: '/transport',
  LIBRARY: '/library',
  PROCUREMENT: '/procurement',
  FACILITIES: '/facilities',
  RESEARCH: '/research',
  ACCREDITATION: '/accreditation',
  CMS: '/cms',
  SETTINGS: '/settings',
  AI: '/ai',
  APIGATEWAY: '/api-gateway',
  DEVOPS: '/devops',
  WORKFLOW: '/workflow',
  WORKFLOW_DESIGNER: '/workflow/designer',
  SEARCH: '/search',
  GRC: '/grc',
  MDM: '/mdm',

} as const;

export type RouteKeys = keyof typeof ROUTES;
export type RouteValues = typeof ROUTES[RouteKeys];
